### ISSUE TITLE
Markdown link under source metadata breaks rendered document

### ISSUE THREAD

**Issue by FekketCantenel** [isaacvando/cookrender#1] opened 2023-01-03 02:25 UTC
User behavior: The following code at the top of a .cook document.

    >> source: [Small Town Woman](https://www.smalltownwoman.com/easy-matzo-ball-soup/)

Expected result: The following Markdown:

    **source:** [Small Town Woman](https://www.smalltownwoman.com/easy-matzo-ball-soup/)

Actual result:

    ## Small Town Woman
    - (https://www\.smalltownwoman\.com/easy\-matzo\-ball\-soup/)
    - [all remaining metadata are bullet-pointed, and ingredients/steps are not rendered]

Markdown links are not specified in [the cooklang metadata spec](https://github.com/cooklang/spec#metadata) and I'm not sure where to request that it be added, since the official repo doesn't have an Issues tab.

**Comment by isaacvando** [comment] 2023-01-03 02:46
Thanks for bringing this up!

Cooklang also has a shopping list specification which is used like this:
```
[Aldi]
Bananas
Peanut butter

[Costco]
Chips
```

This extension uses [cooklang-ts](https://github.com/cooklang/cooklang-ts) to parse the .cook files and the issue here is that cooklang-ts is parsing the markdown link as a shopping list which messes up everything after it. 

As far as I know the Cooklang spec doesn't say if a single .cook file can contain both a recipe and a shopping list but to me it seems like a file should only be allowed to contain one or the other. Right now cooklang-ts will parse recipes and shopping lists in the same file but if that is changed this problem should be resolved.

I would recommend opening an issue on [cooklang-ts](https://github.com/cooklang/cooklang-ts) about the weird behavior that can be caused by having recipes and shopping lists in the same file. I will leave this issue open until cooklang-ts is updated. 

The best workaround I can think of is just leaving off the `[` in the link and then manually updating the .md file after you render but that is certainly not very pleasant.

**Comment by FekketCantenel** [comment] 2023-01-03 02:55
Thanks so much for the rapid reply! As you recommended, I've opened an issue on the parser repo.

**Comment by jack-temko** [comment] 2023-01-04 04:49
Fixed in cooklang/cooklang-ts@ba32ab668ecea2dffdf979d4643fa705885d658e.

Bumped version in pull #4.

**Comment by isaacvando** [comment] 2023-01-04 05:19
The changes are now live! Thanks for making this change so quickly @ThatTSGuy.

**Closed as completed** 2023-01-04 05:19 UTC
